# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: true
bullet: true
html: false
indentation: true
line_length: true
spaces: true
url: false
whitespace: true
