'''
Use create_policy.py to generate suitable policy objects if
needed. Add the result at the end of the class 'strategies'.
'''
from Projects.base.game.hex import pieces

class strategies:
    '''
    A class that has pre-written strategies to use on SVerify.
    Each strategy is described.
    '''

    # ryan 3x4 .25 lower bound strategy (second player)
    ryan_3x4_lower_bound = {
        'name': 'ryan_3x4_lower_bound',
        'description': 'ryan 3x4 lower bound strategy',
        'num_rows': 3,
        'num_cols': 4,
        'player': pieces.kBlack,
        'player_order': 1,
        'first_player': pieces.kWhite,
        'strategy': {
            "............": [8, 3],
            "........o...": [3],
            "...o........": [8],
            "...x....o...": [7],
            "...o....x...": [4],
            "...x...oo...": [6],
            "...oo...x...": [5],
            "...x..xoo...": [10],
            "...oox..x...": [1],
            "...x..xoo.o.": [9],
            ".o.oox..x...": [2],
            "...x...xo...": [11],
            "...ox...x...": [0],
            "...x...xo..o": [10],
            "o..ox...x...": [1],
            "...x...xo.oo": [9],
            "oo.ox...x...": [2],
            "...x...xoxoo": [6],
            "ooxox...x...": [5],
            "...x..oxoxoo": [5],
            "ooxoxo..x...": [6],
            "...x.xoxoxoo": [2],
            "ooxoxox.x...": [9],
            "..ox.xoxoxoo": [1],
            "ooxoxox.xo..": [10],
            "........x...": [4],
            "...x........": [7],
            "....o...x...": [5],
            "...x...o....": [6],
            "....oo..x...": [3],
            "...x..oo....": [8],
            "...xoo..x...": [6, 7],
            "...x..oox...": [5, 4],
            "...xooo.x...": [7],
            "...x.ooox...": [4],
            "...xoooxx...": [11],
            "...xxooox...": [0],
            "...xoooxx..o": [10],
            "o..xxooox...": [1],
            "...xoox.x...": [10],
            "...x.xoox...": [1],
            "...xoox.x.o.": [9],
            ".o.x.xoox...": [2],
            "...xoox.xoo.": [11],
            ".oox.xoox...": [0],
            "...xoox.xoox": [7],
            "xoox.xoox...": [4],
            "...xoo.ox...": [6],
            "...xo.oox...": [5],
            "...xooxox...": [10],
            "...xoxoox...": [1],
            "...xooxox.o.": [9],
            ".o.xoxoox...": [2],
            "...xoo.xx...": [11],
            "...xx.oox...": [0],
            "...xoo.xx..o": [10],
            "o..xx.oox...": [1],
            "...xoo.xx.oo": [6],
            "oo.xx.oox...": [5],
            "...xooxxx.oo": [9],
            "oo.xxxoox...": [2],
            "....ox..x...": [1],
            "...x..xo....": [10],
            ".o..ox..x...": [2],
            "...x..xo..o.": [9],
            ".oo.ox..x...": [3],
            "...x..xo.oo.": [8],
            ".ooxox..x...": [6],
            "...x..xoxoo.": [5],
            ".ooxoxo.x...": [7],
            "...x.oxoxoo.": [4],
            ".ooxoxoxx...": [11],
            "...xxoxoxoo.": [0],
            ".ooxoxoxx..o": [10],
            "o..xxoxoxoo.": [1],
            "....x...x...": [0],
            "...x...x....": [11],
            "o...x...x...": [1],
            "...x...x...o": [10],
            "oo..x...x...": [2, 3],
            "...x...x..oo": [9, 8],
            "ooo.x...x...": [3],
            "...x...x.ooo": [8],
            "oooxx...x...": [7],
            "...x...xxooo": [4],
            "oooxx..ox...": [6],
            "...xo..xxooo": [5],
            "oooxx.xox...": [10],
            "...xox.xxooo": [1],
            "oooxx.xox.o.": [9],
            ".o.xox.xxooo": [2],
            "oooxx..xx...": [11],
            "...xx..xxooo": [0],
            "oooxx..xx..o": [10],
            "o..xx..xxooo": [1],
            "oooxx..xx.oo": [6],
            "oo.xx..xxooo": [5],
            "oooxx.xxx.oo": [9],
            "oo.xxx.xxooo": [2],
            "oooxx.xxxooo": [5],
            "oooxxx.xxooo": [6],
            "oox.x...x...": [5],
            "...x...x.xoo": [6],
            "oox.xo..x...": [7],
            "...x..ox.xoo": [4],
            "oox.xo.ox...": [6],
            "...xo.ox.xoo": [5],
            "oox.xoxox...": [10],
            "...xoxox.xoo": [1],
            "oox.xoxox.o.": [9],
            ".o.xoxox.xoo": [2],
            "oox.xo.xx...": [6],
            "...xx.ox.xoo": [5],
            "oox.xooxx...": [3],
            "...xxoox.xoo": [8],
            "ooxxxooxx...": [11],
            "...xxooxxxoo": [0],
            "ooxxxooxx..o": [10],
            "o..xxooxxxoo": [1],
            "oox.xoxxx...": [11],
            "...xxxox.xoo": [0],
            "oox.xoxxx..o": [10],
            "o..xxxox.xoo": [1],
            "oox.xoxxx.oo": [9],
            "oo.xxxox.xoo": [2],
            "oo.xx...x...": [6, 7],
            "...x...xx.oo": [5, 4],
            "oo.xx.o.x...": [7],
            "...x.o.xx.oo": [4],
            "oo.xx.oxx...": [11],
            "...xxo.xx.oo": [0],
            "oo.xx.oxx..o": [10],
            "o..xxo.xx.oo": [1],
            "oo.xx.oxx.oo": [2],
            "oo.xxo.xx.oo": [9],
            "ooxxx.oxx.oo": [5],
            "oo.xxo.xxxoo": [6],
            "oo.xx.x.x...": [10],
            "...x.x.xx.oo": [1],
            "oo.xx.x.x.o.": [9],
            ".o.x.x.xx.oo": [2],
            "oo.xx.x.xoo.": [5],
            ".oox.x.xx.oo": [6],
            "oo.xxox.xoo.": [11],
            ".oox.xoxx.oo": [0],
            "oo.xxox.xoox": [7],
            "xoox.xoxx.oo": [4],
            "oo.xx..ox...": [5, 6],
            "...xo..xx.oo": [6, 5],
            "oo.xxo.ox...": [6],
            "...xo.oxx.oo": [5],
            "oo.xxoxox...": [10],
            "...xoxoxx.oo": [1],
            "oo.xxoxox.o.": [9],
            ".o.xoxoxx.oo": [2],
            "oo.xxx.ox...": [2],
            "...xo.xxx.oo": [9],
            "oooxxx.ox...": [6],
            "...xo.xxxooo": [5],
            "oo.xx.xox...": [10],
            "...xox.xx.oo": [1],
            "oo.xx.xox.o.": [9],
            ".o.xox.xx.oo": [2],
            "oo.xx.xoxoo.": [5],
            ".ooxox.xx.oo": [6],
            "oo.xx..xx...": [11],
            "...xx..xx.oo": [0],
            "oo.xx..xx..o": [10],
            "o..xx..xx.oo": [1],
            "oo.xx..xx.oo": [5, 6],
            "oo.xxx.xx.oo": [2],
            "oo.xx.xxx.oo": [9],
            "oooxxx.xx.oo": [6],
            "oo.xx.xxxooo": [5],
        }
    }

    test_2x2 = {
        'name': 'test_2x2',
        'description': 'test 2x2',
        'num_rows': 2,
        'num_cols': 2,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'strategy': {
            "....": [1],
            "..x.": [0, 3],
            ".x..": [3, 0],
            "o.x.": [1],
            ".x.o": [2],
            "..xo": [0],
            "ox..": [3],
            "..xx": [0],
            "xx..": [3],
            "o.xx": [1],
            "xx.o": [2],
        }
    }

    test_2x2_66p = {
        'name': 'test_2x2',
        'description': 'test 2x2 win chance of .66',
        'num_rows': 2,
        'num_cols': 2,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'strategy': {
            "....": [0, 1, 2, 3],
            "x...": [3],
            "...x": [0],
            "x..o": [1],
            "o..x": [2],
            ".x..": [2],
            "..x.": [1],
            ".xo.": [3],
            ".ox.": [0],
        }
    }

    # subgame (a 4x3 subgame from ryans strategy)
    test_4x3_1 = {
        'name': 'test_4x3_1',
        'description': 'test 4x3: starting from the board state "pp.yzp..z.o.".',
        'num_rows': 3,
        'num_cols': 4,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'board': 'pp.yzp..z.o.',
        'boards': {
            pieces.kBlack: 'oo.xxo..x.o.',
            pieces.kWhite: 'oo.xxo..x.o.',
        },
        'strategy': {
            "oo.xxo..x.o.": [6, 7],
            ".o.x..oxx.oo": [5, 4],
            "oo.xxox.x.o.": [9],
            ".o.x.xoxx.oo": [2],
            "oo.xxox.xoo.": [11],
            ".oox.xoxx.oo": [0],
            "oo.xxox.xoox": [7],
            "xoox.xoxx.oo": [4],
            "oo.xxo.xx.o.": [11],
            ".o.xx.oxx.oo": [0],
            "oo.xxo.xx.oo": [9],
            "oo.xx.oxx.oo": [2],
            "oo.xxo.xxxoo": [6],
            "ooxxx.oxx.oo": [5],
        }
    }

    test_3x3_1 = {
        'name': 'test_3x3_1',
        'description': 'test 3x3: Strategy for ryan notes 10.6 (pg 107) puzzle 1.',
        'num_rows': 3,
        'num_cols': 3,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'strategy': {
            ".........": [1, 7],
            ".x.......": [5, 6],
            ".......x.": [3, 2],
            ".x...o...": [6],
            "...o...x.": [2],
            ".x...ox..": [4],
            "..xo...x.": [4],
            ".x..oox..": [3],
            "..xoo..x.": [5],
            ".x...x...": [2, 4, 7, 8],
            "...x...x.": [6, 4, 1, 0],
            ".xo..x...": [4],
            "...x..ox.": [4],
            ".xo.ox...": [8],
            "...xo.ox.": [0],
            ".xo.ox..x": [3],
            "x..xo.ox.": [5],
            ".xoxox..x": [6],
            "x..xoxox.": [2],
            ".xo.xx...": [8],
            "...xx.ox.": [0],
            ".xo.xx..o": [7],
            "o..xx.ox.": [1],
            ".xo.xx.oo": [6],
            "oo.xx.ox.": [2],
            ".xx..x...": [8],
            "...x..xx.": [0],
            ".xx..x..o": [7],
            "o..x..xx.": [1],
            ".xx..x.oo": [6],
            "oo.x..xx.": [2],
            ".xx..xxoo": [4],
            "ooxx..xx.": [4],
            ".xx.oxxoo": [3],
            "ooxxo.xx.": [5],
            ".x..ox...": [2],
            "...xo..x.": [6],
            ".xx.ox...": [8],
            "...xo.xx.": [0],
            ".xx.ox..o": [7],
            "o..xo.xx.": [1],
            ".xx.ox.oo": [3, 6],
            "oo.xo.xx.": [5, 2],
            ".xxxox.oo": [6],
            "oo.xoxxx.": [2],
            ".x..xx...": [8],
            "...xx..x.": [0],
            ".x..xx..o": [7],
            "o..xx..x.": [1],
            ".x..xx.oo": [6],
            "oo.xx..x.": [2],
            ".x...x.o.": [8],
            ".o.x...x.": [0],
            ".x...x.oo": [2, 4],
            "oo.x...x.": [6, 4],
            ".x...x.ox": [4],
            "xo.x...x.": [4],
            ".x..ox.ox": [2],
            "xo.xo..x.": [6],
            ".xo.ox.ox": [3, 6],
            "xo.xo.ox.": [5, 2],
            ".xoxox.ox": [6],
            "xo.xoxox.": [2],
            ".xo.oxxox": [3],
            "xoxxo.ox.": [5],
            ".x...x.x.": [2],
            ".x.x...x.": [6],
            ".xo..x.x.": [4],
            ".x.x..ox.": [4],
            ".xo.ox.x.": [3],
            ".x.xo.ox.": [5],
            ".xoxox.x.": [6],
            ".x.xoxox.": [2],
            ".x...x..o": [7],
            "o..x...x.": [1],
            ".x...x.xo": [2],
            "ox.x...x.": [6],
            ".xo..x.xo": [4],
            "ox.x..ox.": [4],
            ".xo.ox.xo": [3, 6],
            "ox.xo.ox.": [5, 2],
            ".xoxox.xo": [6],
            "ox.xoxox.": [2],
            ".xo.oxxxo": [3],
            "oxxxo.ox.": [5],
            ".x...x..x": [2],
            "x..x...x.": [6],
            ".xo..x..x": [4],
            "x..x..ox.": [4],
            ".x....o..": [5],
            "..o....x.": [3],
            ".x...xo..": [2, 8],
            "..ox...x.": [6, 0],
            ".xo..xo..": [4],
            "..ox..ox.": [4],
            ".xo.xxo..": [8],
            "..oxx.ox.": [0],
            ".xo.xxo.o": [7],
            "o.oxx.ox.": [1],
            ".xx..xo..": [8],
            "..ox..xx.": [0],
            ".xx..xo.o": [7],
            "o.ox..xx.": [1],
            ".x...xo.o": [7],
            "o.ox...x.": [1],
            ".x...xoxo": [2],
            "oxox...x.": [6],
            ".xo..xoxo": [4],
            "oxox..ox.": [4],
            ".x...xo.x": [4],
            "x.ox...x.": [4],
            ".x..oxo.x": [2],
            "x.oxo..x.": [6],
            ".x....x..": [4],
            "..x....x.": [4],
            ".x..o.x..": [3],
            "..x.o..x.": [5],
            ".x.oo.x..": [2, 5],
            "..x.oo.x.": [6, 3],
            ".xxoo.x..": [5],
            "..x.ooxx.": [3],
            ".xxooxx..": [8],
            "..xxooxx.": [0],
            ".xxooxx.o": [7],
            "o.xxooxx.": [1],
            ".x.ooxx..": [2],
            "..xxoo.x.": [6],
        },
    }

    test_3x3_1_no_iso = {
        'name': 'test_3x3_1_no_iso',
        'description': 'test 3x3: Strategy for ryan notes 10.6 (pg 107) puzzle 1. Without the isometric strat.',
        'num_rows': 3,
        'num_cols': 3,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'strategy':{
            ".........": [1],
            ".x.......": [5, 6],
            ".x...o...": [6],
            ".x...ox..": [3],
            ".x.o.ox..": [4],
            ".x...x...": [2, 8],
            ".xo..x...": [4],
            ".xo.ox...": [3],
            ".xoxox...": [6],
            ".xo.xx...": [8],
            ".xo.xx..o": [7],
            ".xo.xx.oo": [6],
            ".xx..x...": [8],
            ".xx..x..o": [7],
            ".xx..x.oo": [6],
            ".xx..xxoo": [3],
            ".xxo.xxoo": [4],
            ".x...x..o": [7],
            ".x...x.oo": [6],
            ".x...xxoo": [3],
            ".x.o.xxoo": [4],
            ".x...x.xo": [2],
            ".xo..x.xo": [4],
            ".xo.ox.xo": [3],
            ".xoxox.xo": [6],
            ".x...x..x": [2],
            ".xo..x..x": [4],
            ".xo.ox..x": [3],
            ".xoxox..x": [6],
            ".x....o..": [5],
            ".x...xo..": [2],
            ".xo..xo..": [4],
            ".xo.xxo..": [8],
            ".xo.xxo.o": [7],
            ".xx..xo..": [8],
            ".xx..xo.o": [7],
            ".x....x..": [3],
            ".x.o..x..": [4],
            ".x.oo.x..": [5],
            ".x.ooxx..": [2],
            ".xxooxx..": [8],
            ".xxooxx.o": [7],
        }
    }
