'''
Use create_policy.py to generate suitable policy objects if
needed. Add the result at the end of the class 'strategies'.
'''
from Projects.base.game.hex import pieces

class strategies:
    '''
    A class that has pre-written strategies to use on SVerify.
    Each strategy is described.
    '''

    # ryan 3x4 .25 lower bound strategy (second player)
    ryan_3x4_lower_bound = {
        'name': 'ryan_3x4_lower_bound',
        'description': 'ryan 3x4 lower bound strategy',
        'num_rows': 3,
        'num_cols': 4,
        'player': pieces.kBlack,
        'player_order': 1,
        'strategy': {
            "............": [3],
            "........o...": [3],
            "...o........": [8],
            "...y....o...": [7],
            "...o....z...": [4],
            "...y...oo...": [6],
            "...oo...z...": [5],
            "...y..yoo...": [10],
            "...ooz..z...": [1],
            "...y..yoo.o.": [9],
            ".o.ooz..z...": [2],
            "...y...yo...": [11],
            "...oz...z...": [0],
            "...y...yo..o": [10],
            "o..oz...z...": [1],
            "...y...yo.oo": [9],
            "oo.oz...z...": [2],
            "...y...yozoo": [6],
            "ooyoz...z...": [5],
            "...y..oyozoo": [5],
            "ooyozo..z...": [6],
            "...y.zoyozoo": [1],
            "ooyozoy.z...": [10],
            ".o.y.zoyozoo": [2],
            "ooyozoy.z.o.": [9],
            "........z...": [4],
            "...y........": [7],
            "....o...z...": [5],
            "...y...o....": [6],
            "....oo..z...": [3],
            "...y..oo....": [8],
            "...yoo..z...": [7],
            "...y..ooz...": [4],
            "...yoo.oz...": [6],
            "...yo.ooz...": [5],
            "...yooyoz...": [10],
            "...yozooz...": [1],
            "...yooyoz.o.": [9],
            ".o.yozooz...": [2],
            "...yoo.yz...": [11],
            "...yz.ooz...": [0],
            "...yoo.yz..o": [10],
            "o..yz.ooz...": [1],
            "...yoo.yz.oo": [6],
            "oo.yz.ooz...": [5],
            "...yooyyz.oo": [9],
            "oo.yzzooz...": [2],
            "....oz..z...": [1],
            "...y..yo....": [10],
            ".o..oz..z...": [2],
            "...y..yo..o.": [9],
            ".oo.oz..z...": [3],
            "...y..yo.oo.": [8],
            ".ooyoz..z...": [6],
            "...y..yozoo.": [5],
            ".ooyozo.z...": [7],
            "...y.oyozoo.": [4],
            ".ooyozoyz...": [11],
            "...yzoyozoo.": [0],
            ".ooyozoyz..o": [10],
            "o..yzoyozoo.": [1],
            "....z...z...": [0],
            "...y...y....": [11],
            "o...z...z...": [1],
            "...y...y...o": [10],
            "oo..z...z...": [2, 3],
            "...y...y..oo": [9, 8],
            "ooo.z...z...": [3],
            "...y...y.ooo": [8],
            "oooyz...z...": [7],
            "...y...yzooo": [4],
            "oooyz..oz...": [6],
            "...yo..yzooo": [5],
            "oooyz.yoz...": [10],
            "...yoz.yzooo": [1],
            "oooyz.yoz.o.": [9],
            ".o.yoz.yzooo": [2],
            "oooyz..yz...": [11],
            "...yz..yzooo": [0],
            "oooyz..yz..o": [10],
            "o..yz..yzooo": [1],
            "oooyz..yz.oo": [6],
            "oo.yz..yzooo": [5],
            "oooyz.yyz.oo": [5],
            "oo.yzz.yzooo": [6],
            "oooyzoyyz.oo": [9],
            "oo.yzzoyzooo": [2],
            "ooy.z...z...": [5],
            "...y...y.zoo": [6],
            "ooy.zo..z...": [6],
            "...y..oy.zoo": [5],
            "ooy.zoo.z...": [7],
            "...y.ooy.zoo": [4],
            "ooy.zooxz...": [3],
            "...yxooy.zoo": [8],
            "ooyyzooyz...": [11],
            "...yzooyzzoo": [0],
            "ooyyzooyz..o": [10],
            "o..yzooyzzoo": [1],
            "ooy.zoy.z...": [10],
            "...y.zoy.zoo": [1],
            "ooy.zoy.z.o.": [9],
            ".o.y.zoy.zoo": [2],
            "ooy.zoy.zoo.": [11],
            ".ooy.zoy.zoo": [0],
            "ooy.zoy.zooz": [7],
            "yooy.zoy.zoo": [4],
            "oo.yz...z...": [6, 7],
            "...y...yz.oo": [5, 4],
            "oo.yz.o.z...": [2, 7],
            "...y.o.yz.oo": [9, 4],
            "oooyz.o.z...": [7],
            "...y.o.yzooo": [4],
            "oooyz.oyz...": [11],
            "...yzo.yzooo": [0],
            "oooyz.oyz..o": [10],
            "o..yzo.yzooo": [1],
            "ooyyz.o.z...": [5],
            "...y.o.yzzoo": [6],
            "ooyyzoo.z...": [7],
            "...y.ooyzzoo": [4],
            "oo.yz.oyz...": [11],
            "...yzo.yz.oo": [0],
            "oo.yz.oyz..o": [10],
            "o..yzo.yz.oo": [1],
            "oo.yz.oyz.oo": [2],
            "oo.yzo.yz.oo": [9],
            "ooyyz.oyz.oo": [5],
            "oo.yzo.yzzoo": [6],
            "oo.yz.y.z...": [10],
            "...y.z.yz.oo": [1],
            "oo.yz.y.z.o.": [9],
            ".o.y.z.yz.oo": [2],
            "oo.yz.y.zoo.": [5],
            ".ooy.z.yz.oo": [6],
            "oo.yzoy.zoo.": [7],
            ".ooy.zoyz.oo": [4],
            "oo.yzoyyzoo.": [11],
            ".ooyzzoyz.oo": [0],
            "oo.yz..oz...": [6],
            "...yo..yz.oo": [5],
            "oo.yz.yoz...": [10],
            "...yoz.yz.oo": [1],
            "oo.yz.yoz.o.": [9],
            ".o.yoz.yz.oo": [2],
            "oo.yz.yozoo.": [5],
            ".ooyoz.yz.oo": [6],
            "oo.yz..yz...": [11],
            "...yz..yz.oo": [0],
            "oo.yz..yz..o": [10],
            "o..yz..yz.oo": [1],
            "oo.yz..yz.oo": [5],
            "oo.yz.yyz.oo": [5],
            "oo.yzz.yz.oo": [6],
            "oo.yzoyyz.oo": [9],
            "oo.yzzoyz.oo": [2],
        }
    }

    test_2x2 = {
        'name': 'test_2x2',
        'description': 'test 2x2',
        'num_rows': 2,
        'num_cols': 2,
        'player': pieces.kBlack,
        'player_order': 0,
        'strategy': {
            "....": [1],
            "..z.": [0, 3],
            ".y..": [3, 0],
            "o.z.": [1],
            ".y.o": [2],
            "..zo": [0],
            "oy..": [3],
            "..zz": [0],
            "yy..": [3],
            "o.zz": [1],
            "yy.o": [2],
        }
    }

    test_2x3_33p = {
        'name': 'test_2x3',
        'description': 'test 2x3',
        'num_rows': 2,
        'num_cols': 3,
        'player': pieces.kBlack,
        'player_order': 0,
        'strategy': {
            "......": [2],
            "...z..": [0, 4, 5],
            "..y...": [5, 1, 0],
            "o..z..": [1],
            "..y..o": [4],
            "...zo.": [2],
            ".oy...": [3],
            "..yzo.": [5],
            ".oyz..": [0],
            "..yzoo": [0],
            "ooyz..": [5],
            "...zz.": [5],
            ".yy...": [0],
            "...zzo": [0],
            "oyy...": [5],
            "o..zzo": [1],
            "oyy..o": [4],
            "...zzz": [0],
            "yyy...": [5],
            "o..zzz": [1],
            "yyy..o": [4],
            "oo.zzz": [2],
            "yyy.oo": [3],
            "...z.o": [4],
            "o.y...": [1],
            "...z.z": [4],
            "y.y...": [1],
            "...zoz": [0],
            "yoy...": [5],
            "o..zoz": [1],
            "yoy..o": [4],
        }
    }
