'''
Use create_policy.py to generate suitable policy objects if
needed. Add the result at the end of the class 'strategies'.
'''
from Projects.base.game.hex import pieces

class strategies:
    '''
    A class that has pre-written strategies to use on SVerify.
    Each strategy is described.
    '''
    # subgame (a 4x3 subgame from ryans strategy)
    test_4x3_1 = {
        'name': 'test_4x3_1',
        'description': 'test 4x3: starting from the board state "pp.yzp..z.o.". Expected win probability is 0.5.',
        'num_rows': 3,
        'num_cols': 4,
        'player': pieces.kBlack,
        'player_order': 1,
        'first_player': pieces.kWhite,
        'board': 'pp.yzp..z.o.',
        'boards': {
            pieces.kBlack: 'oo.xxo..x.o.',
            pieces.kWhite: 'oo.xxo..x.o.',
        },
        'strategy': {
            "oo.xxo..x.o.": [(6, 0.5), (7, 0.5)],
            ".o.x..oxx.oo": [(5, 0.5), (4, 0.5)],
            "oo.xxox.x.o.": [(9, 1)],
            ".o.x.xoxx.oo": [(2, 1)],
            "oo.xxox.xoo.": [(11, 1)],
            ".oox.xoxx.oo": [(0, 1)],
            "oo.xxox.xoox": [(7, 1)],
            "xoox.xoxx.oo": [(4, 1)],
            "oo.xxo.xx.o.": [(11, 1)],
            ".o.xx.oxx.oo": [(0, 1)],
            "oo.xxo.xx.oo": [(9, 1)],
            "oo.xx.oxx.oo": [(2, 1)],
            "oo.xxo.xxxoo": [(6, 1)],
            "ooxxx.oxx.oo": [(5, 1)],
        }
    }

    test_2x2_win = {
        'name': 'test_2x2_win',
        'description': '2x2 board, definite win for first player - black. Expected win probability is 1.',
        'num_rows': 2,
        'num_cols': 2,
        'player': pieces.kBlack,
        'player_order': 0,
        'first_player': pieces.kBlack,
        'strategy':{
            "....": [(1, 0.5), (2, 0.5)],
            ".x..": [(2, 1.0)],
            ".xo.": [(3, 1.0)],
            "..x.": [(0, 0.5), (1, 0.5)],
            "o.x.": [(1, 1.0)],
            ".ox.": [(0, 1.0)],
        }
    }
    
    ryan_3x4_subgame_1 = {
		"num_rows": 3,
		"num_cols": 4,
		"description": "A subgame on a 4x3 board based on Ryan's strategy. Expected win probability is 0.5.",
		"player": pieces.kBlack,
		"player_order": 1,
		"first_player": pieces.kWhite,
		"isomorphic": True,
		"board": "pp..zp..z...",
		"boards": {
			pieces.kBlack: "oo..x...x...",
			pieces.kWhite: "oo..xo..x..."
		},
		"strategy": {
			"oo..x...x...": [(2, 0.5), (3, 0.5)],
			"...x...x..oo": [(9, 0.5), (8, 0.5)],
			"ooo.x...x...": [(3, 1.0)],
			"...x...x.ooo": [(8, 1.0)],
			"oooxx...x...": [(7, 1.0)],
			"...x...xxooo": [(4, 1.0)],
			"oooxx..ox...": [(6, 1.0)],
			"...xo..xxooo": [(5, 1.0)],
			"oooxx.xox...": [(10, 1.0)],
			"...xox.xxooo": [(1, 1.0)],
			"oooxx.xox.o.": [(9, 1.0)],
			".o.xox.xxooo": [(2, 1.0)],
			"oooxx..xx...": [(11, 1.0)],
			"...xx..xxooo": [(0, 1.0)],
			"oooxx..xx..o": [(10, 1.0)],
			"o..xx..xxooo": [(1, 1.0)],
			"oooxx..xx.oo": [(6, 1.0)],
			"oo.xx..xxooo": [(5, 1.0)],
			"oooxx.xxx.oo": [(9, 1.0)],
			"oo.xxx.xxooo": [(2, 1.0)],
			"oooxx.xxxooo": [(5, 1.0)],
			"oooxxx.xxooo": [(6, 1.0)],
			"oox.x...x...": [(5, 1.0)],
			"...x...x.xoo": [(6, 1.0)],
			"oox.xo..x...": [(6, 1.0)],
			"...x..ox.xoo": [(5, 1.0)],
			"oox.xoo.x...": [(11, 1.0)],
			"...x.oox.xoo": [(0, 1.0)],
			"oox.xoo.x..x": [(10, 1.0)],
			"x..x.oox.xoo": [(1, 1.0)],
			"oox.xoo.x.ox": [(3, 1.0)],
			"xo.x.oox.xoo": [(8, 1.0)],
			"ooxxxoo.x.ox": [(7, 1.0)],
			"xo.x.ooxxxoo": [(4, 1.0)],
			"oox.xoo.x.xx": [(7, 1.0)],
			"xx.x.oox.xoo": [(4, 1.0)],
			"oox.xooxx.xx": [(3, 1.0)],
			"xx.xxoox.xoo": [(8, 1.0)],
			"oox.xox.x...": [(9, 1.0)],
			"...x.xox.xoo": [(2, 1.0)],
			"oox.xox.xo..": [(10, 1.0)],
			"..ox.xox.xoo": [(1, 1.0)],
			"oox.xox.xoo.": [(11, 1.0)],
			".oox.xox.xoo": [(0, 1.0)],
			"oox.xox.xoox": [(7, 1.0)],
			"xoox.xox.xoo": [(4, 1.0)],
			"oo.ox...x...": [(2, 1.0)],
			"...x...xo.oo": [(9, 1.0)],
			"ooxox...x...": [(5, 1.0)],
			"...x...xoxoo": [(6, 1.0)],
			"ooxoxo..x...": [(6, 1.0)],
			"...x..oxoxoo": [(5, 1.0)],
			"ooxoxox.x...": [(9, 1.0)],
			"...x.xoxoxoo": [(2, 1.0)],
			"ooxoxox.xo..": [(10, 1.0)],
			"..ox.xoxoxoo": [(1, 1.0)],
			"oo.xx...x...": [(7, 1.0)],
			"...x...xx.oo": [(4, 1.0)],
			"oo.xx..ox...": [(6, 1.0)],
			"...xo..xx.oo": [(5, 1.0)],
			"oo.xx.oox...": [(10, 1.0)],
			"...xoo.xx.oo": [(1, 1.0)],
			"oo.xx.oox.x.": [(9, 1.0)],
			".x.xoo.xx.oo": [(2, 1.0)],
			"oo.xx.ooxox.": [(2, 1.0)],
			".xoxoo.xx.oo": [(9, 1.0)],
			"ooxxx.ooxox.": [(11, 1.0)],
			".xoxoo.xxxoo": [(0, 1.0)],
			"ooxxx.ooxoxo": [(5, 1.0)],
			"oxoxoo.xxxoo": [(6, 1.0)],
			"ooxxx.ooxoxx": [(5, 1.0)],
			"xxoxoo.xxxoo": [(6, 1.0)],
			"oo.xx.ooxxx.": [(11, 1.0)],
			".xxxoo.xx.oo": [(0, 1.0)],
			"oo.xx.ooxxxo": [(2, 1.0)],
			"oxxxoo.xx.oo": [(9, 1.0)],
			"ooxxx.ooxxxo": [(5, 1.0)],
			"oxxxoo.xxxoo": [(6, 1.0)],
			"oo.xx.ooxxxx": [(5, 1.0)],
			"xxxxoo.xx.oo": [(6, 1.0)],
			"oo.xxxooxxxx": [(2, 1.0)],
			"xxxxooxxx.oo": [(9, 1.0)],
			"oo.xx.xox...": [(10, 1.0)],
			"...xox.xx.oo": [(1, 1.0)],
			"oo.xx.xox.o.": [(9, 1.0)],
			".o.xox.xx.oo": [(2, 1.0)],
			"oo.xx.xoxoo.": [(5, 1.0)],
			".ooxox.xx.oo": [(6, 1.0)],
			"oo.xx..xx...": [(11, 1.0)],
			"...xx..xx.oo": [(0, 1.0)],
			"oo.xx..xx..o": [(10, 1.0)],
			"o..xx..xx.oo": [(1, 1.0)],
			"oo.xx..xx.oo": [(5, 0.5), (6, 0.5)],
			"oo.xx.oxx.oo": [(5, 1.0)],
			"oo.xxo.xx.oo": [(6, 1.0)],
			"oo.xxxoxx.oo": [(2, 1.0)],
			"oo.xxoxxx.oo": [(9, 1.0)],
			"oo.xx.xxx.oo": [(5, 1.0)],
			"oo.xxx.xx.oo": [(6, 1.0)],
		}
	}

    ryan_3x3_puzzle_1 = {
		"num_rows": 3,
		"num_cols": 3,
		"description": "Ryan's first 3x3 puzzle. Expected win probability is 0.75",
		"player": pieces.kBlack,
		"player_order": 0,
		"first_player": pieces.kBlack,
		"isomorphic": True,
		"board": ".y.......",
		"boards": {
			pieces.kBlack: ".x.......",
			pieces.kWhite: ".x......."
		},
		"strategy": {
			".x.......": [(5, 0.5), (6, 0.5)],
			".......x.": [(3, 0.5), (2, 0.5)],
			".x...o...": [(6, 1.0)],
			"...o...x.": [(2, 1.0)],
			".x...ox..": [(3, 1.0)],
			"..xo...x.": [(5, 1.0)],
			".x.o.ox..": [(4, 1.0)],
			"..xo.o.x.": [(4, 1.0)],
			".x...x...": [(2, 0.5), (4, 0.5)],
			"...x...x.": [(6, 0.5), (4, 0.5)],
			".xo..x...": [(4, 1.0)],
			"...x..ox.": [(4, 1.0)],
			".xo.ox...": [(0, 1.0)],
			"...xo.ox.": [(8, 1.0)],
			"xxo.ox...": [(8, 1.0)],
			"...xo.oxx": [(0, 1.0)],
			"xxo.ox..o": [(6, 1.0)],
			"o..xo.oxx": [(2, 1.0)],
			"xxo.oxx.o": [(3, 1.0)],
			"o.xxo.oxx": [(5, 1.0)],
			"xxo.ox..x": [(3, 1.0)],
			"x..xo.oxx": [(5, 1.0)],
			"xxoxox..x": [(7, 1.0)],
			"x..xoxoxx": [(1, 1.0)],
			"xxoxox.ox": [(6, 1.0)],
			"xo.xoxoxx": [(2, 1.0)],
			"xxoxox.xx": [(6, 1.0)],
			"xx.xoxoxx": [(2, 1.0)],
			".xo.xx...": [(8, 1.0)],
			"...xx.ox.": [(0, 1.0)],
			".xo.xx..o": [(7, 1.0)],
			"o..xx.ox.": [(1, 1.0)],
			".xo.xx.oo": [(6, 1.0)],
			"oo.xx.ox.": [(2, 1.0)],
			".xx..x...": [(8, 1.0)],
			"...x..xx.": [(0, 1.0)],
			".xx..x..o": [(7, 1.0)],
			"o..x..xx.": [(1, 1.0)],
			".xx..x.oo": [(6, 1.0)],
			"oo.x..xx.": [(2, 1.0)],
			".xx..xxoo": [(3, 1.0)],
			"ooxx..xx.": [(5, 1.0)],
			".xxo.xxoo": [(4, 1.0)],
			"ooxx.oxx.": [(4, 1.0)],
			".x..ox...": [(2, 1.0)],
			"...xo..x.": [(6, 1.0)],
			".xx.ox...": [(8, 1.0)],
			"...xo.xx.": [(0, 1.0)],
			".xx.ox..o": [(7, 1.0)],
			"o..xo.xx.": [(1, 1.0)],
			".xx.ox.oo": [(0, 1.0)],
			"oo.xo.xx.": [(8, 1.0)],
			"xxx.ox.oo": [(3, 1.0)],
			"oo.xo.xxx": [(5, 1.0)],
			"xxxxox.oo": [(6, 1.0)],
			"oo.xoxxxx": [(2, 1.0)],
			".x..xx...": [(8, 1.0)],
			"...xx..x.": [(0, 1.0)],
			".x..xx..o": [(7, 1.0)],
			"o..xx..x.": [(1, 1.0)],
			".x..xx.oo": [(6, 1.0)],
			"oo.xx..x.": [(2, 1.0)],
			".x....o..": [(5, 1.0)],
			"..o....x.": [(3, 1.0)],
			".x...xo..": [(2, 0.5), (8, 0.5)],
			"..ox...x.": [(6, 0.5), (0, 0.5)],
			".xo..xo..": [(4, 1.0)],
			"..ox..ox.": [(4, 1.0)],
			".xo.xxo..": [(8, 1.0)],
			"..oxx.ox.": [(0, 1.0)],
			".xo.xxo.o": [(7, 1.0)],
			"o.oxx.ox.": [(1, 1.0)],
			".xx..xo..": [(8, 1.0)],
			"..ox..xx.": [(0, 1.0)],
			".xx..xo.o": [(7, 1.0)],
			"o.ox..xx.": [(1, 1.0)],
			".x...xo.o": [(7, 1.0)],
			"o.ox...x.": [(1, 1.0)],
			".x...xoxo": [(2, 1.0)],
			"oxox...x.": [(6, 1.0)],
			".xo..xoxo": [(4, 1.0)],
			"oxox..ox.": [(4, 1.0)],
			".x...xo.x": [(4, 1.0)],
			"x.ox...x.": [(4, 1.0)],
			".x..oxo.x": [(2, 1.0)],
			"x.oxo..x.": [(6, 1.0)],
			".x....x..": [(3, 1.0)],
			"..x....x.": [(5, 1.0)],
			".x.o..x..": [(4, 1.0)],
			"..x..o.x.": [(4, 1.0)],
			".x.oo.x..": [(7, 1.0)],
			"..x.oo.x.": [(1, 1.0)],
			".x.oo.xx.": [(8, 1.0)],
			".xx.oo.x.": [(0, 1.0)],
			".x.oo.xxo": [(5, 1.0)],
			"oxx.oo.x.": [(3, 1.0)],
			".x.ooxxxo": [(0, 1.0)],
			"oxxxoo.x.": [(8, 1.0)],
			"ox.ooxxxo": [(2, 1.0)],
			"oxxxoo.xo": [(6, 1.0)],
			"xx.ooxxxo": [(2, 1.0)],
			"oxxxoo.xx": [(6, 1.0)],
			".x.oo.xxx": [(0, 1.0)],
			"xxx.oo.x.": [(8, 1.0)],
			"ox.oo.xxx": [(2, 1.0)],
			"xxx.oo.xo": [(6, 1.0)],
			"oxxoo.xxx": [(5, 1.0)],
			"xxx.ooxxo": [(3, 1.0)],
			"xx.oo.xxx": [(2, 1.0)],
			"xxx.oo.xx": [(6, 1.0)],
			"xxxoo.xxx": [(5, 1.0)],
			"xxx.ooxxx": [(3, 1.0)],
		}
	}

    ryan_3x4 = {
		"num_rows": 3,
		"num_cols": 4,
		"description": "Ryan's 3x4 strategy. Win probability is 0.75.",
		"player": pieces.kBlack,
		"player_order": 1,
		"first_player": pieces.kWhite,
		"isomorphic": True,
		"board": "............",
		"boards": {
			pieces.kBlack: "............",
			pieces.kWhite: "............"
		},
		"strategy": {
			"............": [(3, 0.5), (8, 0.5)],
			"........o...": [(3, 1.0)],
			"...o........": [(8, 1.0)],
			"...x....o...": [(7, 1.0)],
			"...o....x...": [(4, 1.0)],
			"...x...oo...": [(6, 1.0)],
			"...oo...x...": [(5, 1.0)],
			"...x..xoo...": [(10, 1.0)],
			"...oox..x...": [(1, 1.0)],
			"...x..xoo.o.": [(9, 1.0)],
			".o.oox..x...": [(2, 1.0)],
			"...x...xo...": [(11, 1.0)],
			"...ox...x...": [(0, 1.0)],
			"...x...xo..o": [(10, 1.0)],
			"o..ox...x...": [(1, 1.0)],
			"...x...xo.oo": [(9, 1.0)],
			"oo.ox...x...": [(2, 1.0)],
			"...x...xoxoo": [(6, 1.0)],
			"ooxox...x...": [(5, 1.0)],
			"...x..oxoxoo": [(5, 1.0)],
			"ooxoxo..x...": [(6, 1.0)],
			"...x.xoxoxoo": [(2, 1.0)],
			"ooxoxox.x...": [(9, 1.0)],
			"..ox.xoxoxoo": [(1, 1.0)],
			"ooxoxox.xo..": [(10, 1.0)],
			"........x...": [(4, 1.0)],
			"...x........": [(7, 1.0)],
			"....o...x...": [(5, 1.0)],
			"...x...o....": [(6, 1.0)],
			"....oo..x...": [(3, 1.0)],
			"...x..oo....": [(8, 1.0)],
			"...xoo..x...": [(6, 0.5), (7, 0.5)],
			"...x..oox...": [(5, 0.5), (4, 0.5)],
			"...xooo.x...": [(7, 1.0)],
			"...x.ooox...": [(4, 1.0)],
			"...xoooxx...": [(11, 1.0)],
			"...xxooox...": [(0, 1.0)],
			"...xoooxx..o": [(10, 1.0)],
			"o..xxooox...": [(1, 1.0)],
			"...xoox.x...": [(10, 1.0)],
			"...x.xoox...": [(1, 1.0)],
			"...xoox.x.o.": [(9, 1.0)],
			".o.x.xoox...": [(2, 1.0)],
			"...xoox.xoo.": [(7, 1.0)],
			".oox.xoox...": [(4, 1.0)],
			"...xooxxxoo.": [(2, 1.0)],
			".ooxxxoox...": [(9, 1.0)],
			"..oxooxxxoo.": [(0, 1.0)],
			".ooxxxooxo..": [(11, 1.0)],
			"x.oxooxxxoo.": [(1, 1.0)],
			".ooxxxooxo.x": [(10, 1.0)],
			"xooxooxxxoo.": [(11, 1.0)],
			".ooxxxooxoox": [(0, 1.0)],
			"xxoxooxxxoo.": [(11, 1.0)],
			".ooxxxooxoxx": [(0, 1.0)],
			"..xxooxxxoo.": [(1, 1.0)],
			".ooxxxooxx..": [(10, 1.0)],
			".oxxooxxxoo.": [(0, 1.0)],
			".ooxxxooxxo.": [(11, 1.0)],
			"ooxxooxxxoo.": [(11, 1.0)],
			".ooxxxooxxoo": [(0, 1.0)],
			"xoxxooxxxoo.": [(11, 1.0)],
			".ooxxxooxxox": [(0, 1.0)],
			".xxxooxxxoo.": [(0, 1.0)],
			".ooxxxooxxx.": [(11, 1.0)],
			"oxxxooxxxoo.": [(11, 1.0)],
			".ooxxxooxxxo": [(0, 1.0)],
			"xxxxooxxxoo.": [(11, 1.0)],
			".ooxxxooxxxx": [(0, 1.0)],
			"...xoo.ox...": [(6, 1.0)],
			"...xo.oox...": [(5, 1.0)],
			"...xooxox...": [(9, 1.0)],
			"...xoxoox...": [(2, 1.0)],
			"...xooxoxo..": [(10, 1.0)],
			"..oxoxoox...": [(1, 1.0)],
			"...xoo.xx...": [(10, 1.0)],
			"...xx.oox...": [(1, 1.0)],
			"...xoo.xx.o.": [(11, 1.0)],
			".o.xx.oox...": [(0, 1.0)],
			"...xoo.xx.oo": [(2, 1.0)],
			"oo.xx.oox...": [(9, 1.0)],
			"..xxoo.xx.oo": [(6, 1.0)],
			"oo.xx.ooxx..": [(5, 1.0)],
			"..xxooxxx.oo": [(1, 1.0)],
			"oo.xxxooxx..": [(10, 1.0)],
			".oxxooxxx.oo": [(0, 1.0)],
			"oo.xxxooxxo.": [(11, 1.0)],
			"ooxxooxxx.oo": [(9, 1.0)],
			"oo.xxxooxxoo": [(2, 1.0)],
			"xoxxooxxx.oo": [(9, 1.0)],
			"oo.xxxooxxox": [(2, 1.0)],
			".xxxooxxx.oo": [(9, 1.0)],
			"oo.xxxooxxx.": [(2, 1.0)],
			"....ox..x...": [(1, 1.0)],
			"...x..xo....": [(10, 1.0)],
			".o..ox..x...": [(2, 1.0)],
			"...x..xo..o.": [(9, 1.0)],
			".oo.ox..x...": [(3, 1.0)],
			"...x..xo.oo.": [(8, 1.0)],
			".ooxox..x...": [(6, 1.0)],
			"...x..xoxoo.": [(5, 1.0)],
			".ooxoxo.x...": [(7, 1.0)],
			"...x.oxoxoo.": [(4, 1.0)],
			".ooxoxoxx...": [(10, 1.0)],
			"...xxoxoxoo.": [(1, 1.0)],
			".ooxoxoxx.o.": [(11, 1.0)],
			".o.xxoxoxoo.": [(0, 1.0)],
			"....x...x...": [(0, 1.0)],
			"...x...x....": [(11, 1.0)],
			"o...x...x...": [(1, 1.0)],
			"...x...x...o": [(10, 1.0)],
			"oo..x...x...": [(2, 0.5), (3, 0.5)],
			"...x...x..oo": [(9, 0.5), (8, 0.5)],
			"ooo.x...x...": [(3, 1.0)],
			"...x...x.ooo": [(8, 1.0)],
			"oooxx...x...": [(7, 1.0)],
			"...x...xxooo": [(4, 1.0)],
			"oooxx..ox...": [(6, 1.0)],
			"...xo..xxooo": [(5, 1.0)],
			"oooxx.xox...": [(10, 1.0)],
			"...xox.xxooo": [(1, 1.0)],
			"oooxx.xox.o.": [(9, 1.0)],
			".o.xox.xxooo": [(2, 1.0)],
			"oooxx..xx...": [(11, 1.0)],
			"...xx..xxooo": [(0, 1.0)],
			"oooxx..xx..o": [(10, 1.0)],
			"o..xx..xxooo": [(1, 1.0)],
			"oooxx..xx.oo": [(6, 1.0)],
			"oo.xx..xxooo": [(5, 1.0)],
			"oooxx.xxx.oo": [(9, 1.0)],
			"oo.xxx.xxooo": [(2, 1.0)],
			"oooxx.xxxooo": [(5, 1.0)],
			"oooxxx.xxooo": [(6, 1.0)],
			"oox.x...x...": [(5, 1.0)],
			"...x...x.xoo": [(6, 1.0)],
			"oox.xo..x...": [(6, 0.5), (7, 0.5)],
			"...x..ox.xoo": [(5, 0.5), (4, 0.5)],
			"oox.xoo.x...": [(3, 1.0)],
			"...x.oox.xoo": [(8, 1.0)],
			"ooxxxoo.x...": [(9, 1.0)],
			"...x.ooxxxoo": [(2, 1.0)],
			"ooxxxoo.xo..": [(7, 1.0)],
			"..ox.ooxxxoo": [(4, 1.0)],
			"ooxxxooxxo..": [(11, 1.0)],
			"..oxxooxxxoo": [(0, 1.0)],
			"ooxxxooxxo.o": [(10, 1.0)],
			"o.oxxooxxxoo": [(1, 1.0)],
			"ooxxxoo.xx..": [(7, 1.0)],
			"..xx.ooxxxoo": [(4, 1.0)],
			"ooxxxooxxx..": [(10, 1.0)],
			"..xxxooxxxoo": [(1, 1.0)],
			"ooxxxooxxxo.": [(11, 1.0)],
			".oxxxooxxxoo": [(0, 1.0)],
			"oox.xox.x...": [(10, 1.0)],
			"...x.xox.xoo": [(1, 1.0)],
			"oox.xox.x.o.": [(9, 1.0)],
			".o.x.xox.xoo": [(2, 1.0)],
			"oox.xox.xoo.": [(7, 1.0)],
			".oox.xox.xoo": [(4, 1.0)],
			"oox.xoxxxoo.": [(11, 1.0)],
			".ooxxxox.xoo": [(0, 1.0)],
			"oox.xo.ox...": [(6, 1.0)],
			"...xo.ox.xoo": [(5, 1.0)],
			"oox.xoxox...": [(10, 1.0)],
			"...xoxox.xoo": [(1, 1.0)],
			"oox.xoxox.o.": [(9, 1.0)],
			".o.xoxox.xoo": [(2, 1.0)],
			"oox.xo.xx...": [(3, 0.5), (11, 0.5)],
			"...xx.ox.xoo": [(8, 0.5), (0, 0.5)],
			"ooxoxo.xx...": [(6, 1.0)],
			"...xx.oxoxoo": [(5, 1.0)],
			"ooxoxoxxx...": [(11, 1.0)],
			"...xxxoxoxoo": [(0, 1.0)],
			"ooxoxoxxx..o": [(10, 1.0)],
			"o..xxxoxoxoo": [(1, 1.0)],
			"ooxoxoxxx.oo": [(9, 1.0)],
			"oo.xxxoxoxoo": [(2, 1.0)],
			"ooxxxo.xx...": [(11, 1.0)],
			"...xx.oxxxoo": [(0, 1.0)],
			"ooxxxo.xx..o": [(10, 1.0)],
			"o..xx.oxxxoo": [(1, 1.0)],
			"ooxxxo.xx.oo": [(6, 1.0)],
			"oo.xx.oxxxoo": [(5, 1.0)],
			"ooxxxoxxx.oo": [(9, 1.0)],
			"oo.xxxoxxxoo": [(2, 1.0)],
			"oox.xo.xx..o": [(10, 1.0)],
			"o..xx.ox.xoo": [(1, 1.0)],
			"oox.xo.xx.oo": [(3, 1.0)],
			"oo.xx.ox.xoo": [(8, 1.0)],
			"oox.xo.xx.xo": [(3, 1.0)],
			"ox.xx.ox.xoo": [(8, 1.0)],
			"ooxoxo.xx.xo": [(6, 1.0)],
			"ox.xx.oxoxoo": [(5, 1.0)],
			"oox.xo.xx..x": [(3, 1.0)],
			"x..xx.ox.xoo": [(8, 1.0)],
			"ooxoxo.xx..x": [(6, 1.0)],
			"x..xx.oxoxoo": [(5, 1.0)],
			"oo.xx...x...": [(6, 0.5), (7, 0.5)],
			"...x...xx.oo": [(5, 0.5), (4, 0.5)],
			"oo.xx.o.x...": [(7, 1.0)],
			"...x.o.xx.oo": [(4, 1.0)],
			"oo.xx.oxx...": [(11, 1.0)],
			"...xxo.xx.oo": [(0, 1.0)],
			"oo.xx.oxx..o": [(10, 1.0)],
			"o..xxo.xx.oo": [(1, 1.0)],
			"oo.xx.oxx.oo": [(2, 1.0)],
			"oo.xxo.xx.oo": [(9, 1.0)],
			"ooxxx.oxx.oo": [(9, 1.0)],
			"oo.xxo.xxxoo": [(2, 1.0)],
			"ooxxx.oxxooo": [(5, 1.0)],
			"oooxxo.xxxoo": [(6, 1.0)],
			"ooxxx.oxxxoo": [(5, 1.0)],
			"ooxxxo.xxxoo": [(6, 1.0)],
			"oo.xx.x.x...": [(9, 1.0)],
			"...x.x.xx.oo": [(2, 1.0)],
			"oo.xx.x.xo..": [(5, 1.0)],
			"..ox.x.xx.oo": [(6, 1.0)],
			"oo.xxox.xo..": [(10, 1.0)],
			"..ox.xoxx.oo": [(1, 1.0)],
			"oo.xxox.xoo.": [(11, 1.0)],
			".oox.xoxx.oo": [(0, 1.0)],
			"oo.xxox.xoox": [(2, 1.0)],
			"xoox.xoxx.oo": [(9, 1.0)],
			"oooxxox.xoox": [(7, 1.0)],
			"xoox.xoxxooo": [(4, 1.0)],
			"ooxxxox.xoox": [(7, 1.0)],
			"xoox.xoxxxoo": [(4, 1.0)],
			"oo.xx..ox...": [(6, 1.0)],
			"...xo..xx.oo": [(5, 1.0)],
			"oo.xx.xox...": [(10, 1.0)],
			"...xox.xx.oo": [(1, 1.0)],
			"oo.xx.xox.o.": [(9, 1.0)],
			".o.xox.xx.oo": [(2, 1.0)],
			"oo.xx.xoxoo.": [(5, 1.0)],
			".ooxox.xx.oo": [(6, 1.0)],
			"oo.xx..xx...": [(11, 1.0)],
			"...xx..xx.oo": [(0, 1.0)],
			"oo.xx..xx..o": [(10, 1.0)],
			"o..xx..xx.oo": [(1, 1.0)],
			"oo.xx..xx.oo": [(5, 0.5), (6, 0.5)],
			"oo.xx.xxx.oo": [(5, 1.0)],
			"oo.xxx.xx.oo": [(6, 1.0)],
			"oo.xxoxxx.oo": [(9, 1.0)],
			"oo.xxxoxx.oo": [(2, 1.0)],
		}
	} 
	
    win_3x3 = {
		"num_rows": 3,
		"num_cols": 3,
		"description": "3x3 probability one win strategy. Win probability is 1.0",
		"player": pieces.kBlack,
		"player_order": 0,
		"first_player": pieces.kBlack,
		"isomorphic": True,
		"board": ".........",
		"boards": {
			pieces.kBlack: ".........",
			pieces.kWhite: "........."
		},
		"strategy": {
			".........": [(2, 0.5), (6, 0.5)],
			"......x..": [(3, 1.0)],
			"..x......": [(5, 1.0)],
			"...o..x..": [(4, 1.0)],
			"..x..o...": [(4, 1.0)],
			"...ox.x..": [(1, 1.0)],
			"..x.xo...": [(7, 1.0)],
			".o.ox.x..": [(2, 1.0)],
			"..x.xo.o.": [(6, 1.0)],
			"...x..x..": [(0, 1.0)],
			"..x..x...": [(8, 1.0)],
			"o..x..x..": [(1, 1.0)],
			"..x..x..o": [(7, 1.0)],
			"oo.x..x..": [(2, 1.0)],
			"..x..x.oo": [(6, 1.0)],
			"ooxx..x..": [(4, 1.0)],
			"..x..xxoo": [(4, 1.0)],
			"ooxxo.x..": [(5, 1.0)],
			"..x.oxxoo": [(3, 1.0)],
			"ooxxoxx..": [(7, 1.0)],
			"..xxoxxoo": [(1, 1.0)],
			"ooxxoxxo.": [(8, 1.0)],
			".oxxoxxoo": [(0, 1.0)],
		}
	}
    
    ryan_3x3_puzzle2 = {
		"num_rows": 3,
		"num_cols": 3,
		"player": pieces.kBlack,
		"player_order": 0,
		"first_player": pieces.kBlack,
		"isomorphic": True,
		"board": "...x.....",
		"boards": {
			pieces.kBlack: "...x.....",
			pieces.kWhite: "...x....."
		},
		"strategy": {
			"...x.....": [(6, 1.0)],
			".....x...": [(2, 1.0)],
			"...x..o..": [(4, 0.2), (5, 0.8)],
			"..o..x...": [(4, 0.2), (3, 0.8)],
			"...xx.o..": [(7, 1.0)],
			"..o.xx...": [(1, 1.0)],
			"...xx.oo.": [(1, 1.0)],
			".oo.xx...": [(7, 1.0)],
			".x.xx.oo.": [(0, 1.0)],
			".oo.xx.x.": [(8, 1.0)],
			"ox.xx.oo.": [(8, 1.0)],
			".oo.xx.xo": [(0, 1.0)],
			"ox.xx.oox": [(5, 1.0)],
			"xoo.xx.xo": [(3, 1.0)],
			"xx.xx.oo.": [(8, 1.0)],
			".oo.xx.xx": [(0, 1.0)],
			"xx.xx.oox": [(5, 1.0)],
			"xoo.xx.xx": [(3, 1.0)],
			"...xx.ox.": [(0, 1.0)],
			".xo.xx...": [(8, 1.0)],
			"o..xx.ox.": [(1, 1.0)],
			".xo.xx..o": [(7, 1.0)],
			"oo.xx.ox.": [(2, 1.0)],
			".xo.xx.oo": [(6, 1.0)],
			"...x.xo..": [(7, 0.5), (4, 0.25), (2, 0.125), (4, 0.125)],
			"..ox.x...": [(1, 0.5), (4, 0.25), (6, 0.125), (4, 0.125)],
			"...x.xoo.": [(8, 1.0)],
			".oox.x...": [(0, 1.0)],
			"...x.xoox": [(2, 0.5), (4, 0.5)],
			"xoox.x...": [(6, 0.5), (4, 0.5)],
			"..ox.xoox": [(4, 1.0)],
			"xoox.xo..": [(4, 1.0)],
			"..oxxxoox": [(0, 1.0)],
			"xooxxxo..": [(8, 1.0)],
			"o.oxxxoox": [(1, 1.0)],
			"xooxxxo.o": [(7, 1.0)],
			"...xoxoox": [(2, 1.0)],
			"xooxox...": [(6, 1.0)],
			"...xxxoox": [(1, 1.0)],
			"xooxxx...": [(7, 1.0)],
			".o.xxxoox": [(0, 1.0)],
			"xooxxx.o.": [(8, 1.0)],
			"oo.xxxoox": [(2, 1.0)],
			"xooxxx.oo": [(6, 1.0)],
			"...x.xox.": [(4, 0.5), (2, 0.5)],
			".xox.x...": [(4, 0.5), (6, 0.5)],
			"...xoxox.": [(2, 1.0)],
			".xoxox...": [(6, 1.0)],
			"...xxxox.": [(0, 1.0)],
			".xoxxx...": [(8, 1.0)],
			"o..xxxox.": [(1, 1.0)],
			".xoxxx..o": [(7, 1.0)],
			"oo.xxxox.": [(2, 1.0)],
			".xoxxx.oo": [(6, 1.0)],
			"..ox.xox.": [(4, 1.0)],
			".xox.xo..": [(4, 1.0)],
			"..oxxxox.": [(0, 1.0)],
			".xoxxxo..": [(8, 1.0)],
			"o.oxxxox.": [(1, 1.0)],
			".xoxxxo.o": [(7, 1.0)],
			"...xoxo..": [(2, 1.0)],
			"..oxox...": [(6, 1.0)],
			"..xxoxo..": [(7, 1.0)],
			"..oxoxx..": [(1, 1.0)],
			"..xxoxoo.": [(8, 1.0)],
			".ooxoxx..": [(0, 1.0)],
			"...xxxo..": [(0, 0.5), (7, 0.5)],
			"..oxxx...": [(8, 0.5), (1, 0.5)],
			"o..xxxo..": [(1, 1.0)],
			"..oxxx..o": [(7, 1.0)],
			"oo.xxxo..": [(2, 1.0)],
			"..oxxx.oo": [(6, 1.0)],
			"ooxxxxo..": [(7, 1.0)],
			"..oxxxxoo": [(1, 1.0)],
			"ooxxxxoo.": [(8, 1.0)],
			".ooxxxxoo": [(0, 1.0)],
			"ox.xxxo..": [(7, 1.0)],
			"..oxxx.xo": [(1, 1.0)],
			"ox.xxxoo.": [(8, 1.0)],
			".ooxxx.xo": [(0, 1.0)],
			"x..xxxo..": [(7, 1.0)],
			"..oxxx..x": [(1, 1.0)],
			"x..xxxoo.": [(8, 1.0)],
			".ooxxx..x": [(0, 1.0)],
			"...xxxoo.": [(8, 1.0)],
			".ooxxx...": [(0, 1.0)],
			"..ox.xo..": [(4, 1.0)],
			"..oxxxo..": [(8, 0.5), (0, 0.5)],
			"o.oxxxo..": [(1, 1.0)],
			"..oxxxo.o": [(7, 1.0)],
			"oxoxxxo..": [(8, 1.0)],
			"..oxxxoxo": [(0, 1.0)],
			"oxoxxxo.o": [(7, 1.0)],
			"o.oxxxoxo": [(1, 1.0)],
			"x.oxxxo..": [(8, 1.0)],
			"..oxxxo.x": [(0, 1.0)],
			"x.oxxxo.o": [(7, 1.0)],
			"o.oxxxo.x": [(1, 1.0)],
			"..xx.xo..": [(8, 1.0)],
			"..ox.xx..": [(0, 1.0)],
			"..xx.xo.o": [(7, 1.0)],
			"o.ox.xx..": [(1, 1.0)],
			"...x..x..": [(0, 1.0)],
			"..x..x...": [(8, 1.0)],
			"o..x..x..": [(1, 1.0)],
			"..x..x..o": [(7, 1.0)],
			"oo.x..x..": [(2, 1.0)],
			"..x..x.oo": [(6, 1.0)],
			"ooxx..x..": [(4, 1.0)],
			"..x..xxoo": [(4, 1.0)],
			"ooxxo.x..": [(5, 1.0)],
			"..x.oxxoo": [(3, 1.0)],
			"ooxxoxx..": [(7, 1.0)],
			"..xxoxxoo": [(1, 1.0)],
			"ooxxoxxo.": [(8, 1.0)],
			".oxxoxxoo": [(0, 1.0)],
		}
	}